### ISSUE TITLE
RuntimeError: The size of tensor a (9) must match the size of tensor b (8) at non-singleton dimension 3

### ISSUE THREAD

**Issue by jdmcgraw** [YongWookHa/swin-transformer-ocr#12]
Following the full steps from the README, I'm running the model with the default test dataset. No modifications made.

Packages were installed according to the requirements.txt.

> C:\Users\Josh\anaconda3\envs\GamePlayer\python.exe C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/run.py
> C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2228.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> setting: {'image_dir': 'C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/dataset/images', 'train_data': 'C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/dataset/train.txt', 'val_data': 'C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/dataset/val.txt', 'tokenizer': 'C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/dataset/tokenizer.pkl', 'save_path': 'C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/checkpoints', 'name': 'transformer-ocr test', 'epochs': 20, 'optimizer': 'AdamW', 'lr': '1e-4', 'scheduler': 'CustomCosineAnnealingWarmupRestarts', 'scheduler_interval': 'step', 'scheduler_param': {'first_cycle_steps': 3000, 'cycle_mult': 3, 'max_lr': 0.0002, 'min_lr': 5e-05, 'warmup_steps': 500, 'gamma': 0.707}, 'width': 448, 'height': 112, 'channels': 3, 'encoder_dim': 96, 'patch_size': 4, 'window_size': 7, 'encoder_depth': [2, 6, 2], 'encoder_heads': [6, 12, 24], 'max_seq_len': 32, 'decoder_dim': 384, 'decoder_heads': 8, 'decoder_depth': 4, 'decoder_cfg': {'cross_attend': True, 'ff_glu': False, 'attn_on_attn': False, 'use_scalenorm': False, 'rel_pos_bias': False}, 'seed': 42, 'temperature': 0.2, 'pad': False, 'pad_token': 0, 'bos_token': 1, 'eos_token': 2, 'oov_token': 3, 'setting': 'settings/default.yaml', 'version': 0, 'load_tokenizer': '', 'num_workers': 0, 'batch_size': 4, 'resume_train': ''}
> 8 data loaded. (0 data skipped)
> 2 data loaded. (0 data skipped)
> tokenizer saved in C:/Users/Josh/Desktop/OCRS/swin-transformer-ocr-main/checkpoints/version_0/transformer-ocr_test.pkl
> GPU available: True, used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
> 
>   | Name    | Type                  | Params
> --------------------------------------------------
> 0 | encoder | CustomSwinTransformer | 6.8 M 
> 1 | decoder | CustomARWrapper       | 11.1 M
> --------------------------------------------------
> 17.9 M    Trainable params
> 0         Non-trainable params
> 17.9 M    Total params
> 71.621    Total estimated model params size (MB)
> C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py:623: UserWarning: Checkpoint directory C:\Users\Josh\Desktop\OCRS\swin-transformer-ocr-main\checkpoints\version_0 exists and is not empty.
>   rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
> Validation sanity check:   0%|          | 0/1 [00:00<?, ?it/s]C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\data_loading.py:111: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 24 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
>   rank_zero_warn(
> Traceback (most recent call last):
>   File "C:\Users\Josh\Desktop\OCRS\swin-transformer-ocr-main\run.py", line 77, in <module>
>     trainer.fit(model, train_dataloaders=train_dataloader, val_dataloaders=valid_dataloader)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 737, in fit
>     self._call_and_handle_interrupt(
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 682, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 772, in _fit_impl
>     self._run(model, ckpt_path=ckpt_path)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1195, in _run
>     self._dispatch()
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1274, in _dispatch
>     self.training_type_plugin.start_training(self)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
>     self._results = trainer.run_stage()
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1284, in run_stage
>     return self._run_train()
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1306, in _run_train
>     self._run_sanity_check(self.lightning_module)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1370, in _run_sanity_check
>     self._evaluation_loop.run()
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
>     self.advance(*args, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 109, in advance
>     dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
>     self.advance(*args, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 122, in advance
>     output = self._evaluation_step(batch, batch_idx, dataloader_idx)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 217, in _evaluation_step
>     output = self.trainer.accelerator.validation_step(step_kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 236, in validation_step
>     return self.training_type_plugin.validation_step(*step_kwargs.values())
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 219, in validation_step
>     return self.model.validation_step(*args, **kwargs)
>   File "C:\Users\Josh\Desktop\OCRS\swin-transformer-ocr-main\models.py", line 99, in validation_step
>     loss = self.decoder(tgt_seq, mask=tgt_mask, context=encoded)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\x_transformers\autoregressive_wrapper.py", line 135, in forward
>     out = self.net(inp, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\x_transformers\x_transformers.py", line 1342, in forward
>     x = self.attn_layers(x, mask = mask, mems = mems, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\x_transformers\x_transformers.py", line 1095, in forward
>     out, inter = block(x, mask = mask, context_mask = self_attn_context_mask, attn_mask = attn_mask, rel_pos = self.rel_pos, rotary_pos_emb = rotary_pos_emb, prev_attn = prev_attn, mem = layer_mem)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Josh\anaconda3\envs\GamePlayer\lib\site-packages\x_transformers\x_transformers.py", line 778, in forward
>     dots = dots.masked_fill(~input_mask, mask_value)
**> RuntimeError: The size of tensor a (9) must match the size of tensor b (8) at non-singleton dimension 3**
> 
> Process finished with exit code 1

<hr>

**Config:** `default.yaml`

> # Input/Output/Name
> image_dir: "dataset/images"
> train_data: "dataset/train.txt"
> val_data: "dataset/val.txt"
> tokenizer: "dataset/tokenizer.pkl"
> save_path: "checkpoints"
> name: "transformer-ocr test"
> 
> epochs: 20
> 
> # Optimizer configurations
> optimizer: "AdamW"
> lr: 1e-4
> scheduler: "CustomCosineAnnealingWarmupRestarts"
> scheduler_interval: "step"
> scheduler_param:
>   first_cycle_steps: 3000
>   cycle_mult: 3
>   max_lr: 0.0002
>   min_lr: 0.00005
>   warmup_steps: 500
>   gamma: 0.707
> 
> # Parameters for model architectures
> width: 448
> height: 112
> channels: 3
> 
> # Encoder
> encoder_dim: 96
> patch_size: 4
> window_size: 7
> encoder_depth: [2, 6, 2]
> encoder_heads: [6, 12, 24]
> 
> # Decoder
> max_seq_len: 32
> decoder_dim: 384
> decoder_heads: 8
> decoder_depth: 4
> decoder_cfg: 
>   cross_attend: true
>   ff_glu: false
>   attn_on_attn: false
>   use_scalenorm: false
>   rel_pos_bias: false
> 
> # Other
> seed: 42
> temperature: 0.2
> pad: False
> 
> # Token ids
> pad_token: 0
> bos_token: 1
> eos_token: 2
> oov_token: 3

I'll follow up on this thread if I resolve the issue. 
감사합니다!

**Comment by jdmcgraw** [comment]
This error was due to some library versioning, but it's not evident which of the packages introduced this issue. (It's likely x-transformers).

To resolve the issue, I created a new venv and modified the line `setuptools==49.6.0.post20210108` in requirements.txt to `setuptools==49.6.0`, then reinstalled requirements with `pip install -r requirements.txt`
